// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/kv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mutacion_Tipo int32

const (
	Mutacion_GUARDAR  Mutacion_Tipo = 0
	Mutacion_ELIMINAR Mutacion_Tipo = 1
)

// Enum value maps for Mutacion_Tipo.
var (
	Mutacion_Tipo_name = map[int32]string{
		0: "GUARDAR",
		1: "ELIMINAR",
	}
	Mutacion_Tipo_value = map[string]int32{
		"GUARDAR":  0,
		"ELIMINAR": 1,
	}
)

func (x Mutacion_Tipo) Enum() *Mutacion_Tipo {
	p := new(Mutacion_Tipo)
	*p = x
	return p
}

func (x Mutacion_Tipo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mutacion_Tipo) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_kv_proto_enumTypes[0].Descriptor()
}

func (Mutacion_Tipo) Type() protoreflect.EnumType {
	return &file_proto_kv_proto_enumTypes[0]
}

func (x Mutacion_Tipo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mutacion_Tipo.Descriptor instead.
func (Mutacion_Tipo) EnumDescriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{6, 0}
}

// Solicitud para Obtener valor según una clave.
type SolicitudObtener struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clave         string                 `protobuf:"bytes,1,opt,name=clave,proto3" json:"clave,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudObtener) Reset() {
	*x = SolicitudObtener{}
	mi := &file_proto_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudObtener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudObtener) ProtoMessage() {}

func (x *SolicitudObtener) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudObtener.ProtoReflect.Descriptor instead.
func (*SolicitudObtener) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{0}
}

func (x *SolicitudObtener) GetClave() string {
	if x != nil {
		return x.Clave
	}
	return ""
}

// Respuesta de Obtener: contiene valor (bytes), reloj vectorial y flag “existe”.
type RespuestaObtener struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valor         []byte                 `protobuf:"bytes,1,opt,name=valor,proto3" json:"valor,omitempty"`
	RelojVector   []byte                 `protobuf:"bytes,2,opt,name=relojVector,proto3" json:"relojVector,omitempty"` // Reloj vectorial serializado
	Existe        bool                   `protobuf:"varint,3,opt,name=existe,proto3" json:"existe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespuestaObtener) Reset() {
	*x = RespuestaObtener{}
	mi := &file_proto_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaObtener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaObtener) ProtoMessage() {}

func (x *RespuestaObtener) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaObtener.ProtoReflect.Descriptor instead.
func (*RespuestaObtener) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{1}
}

func (x *RespuestaObtener) GetValor() []byte {
	if x != nil {
		return x.Valor
	}
	return nil
}

func (x *RespuestaObtener) GetRelojVector() []byte {
	if x != nil {
		return x.RelojVector
	}
	return nil
}

func (x *RespuestaObtener) GetExiste() bool {
	if x != nil {
		return x.Existe
	}
	return false
}

// Solicitud para Guardar (clave, valor).
// El campo relojVector solo se usa si el cliente trae su propio vector; puede quedar vacío.
type SolicitudGuardar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clave         string                 `protobuf:"bytes,1,opt,name=clave,proto3" json:"clave,omitempty"`
	Valor         []byte                 `protobuf:"bytes,2,opt,name=valor,proto3" json:"valor,omitempty"`
	RelojVector   []byte                 `protobuf:"bytes,3,opt,name=relojVector,proto3" json:"relojVector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudGuardar) Reset() {
	*x = SolicitudGuardar{}
	mi := &file_proto_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudGuardar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudGuardar) ProtoMessage() {}

func (x *SolicitudGuardar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudGuardar.ProtoReflect.Descriptor instead.
func (*SolicitudGuardar) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{2}
}

func (x *SolicitudGuardar) GetClave() string {
	if x != nil {
		return x.Clave
	}
	return ""
}

func (x *SolicitudGuardar) GetValor() []byte {
	if x != nil {
		return x.Valor
	}
	return nil
}

func (x *SolicitudGuardar) GetRelojVector() []byte {
	if x != nil {
		return x.RelojVector
	}
	return nil
}

// Respuesta de Guardar: éxito y el nuevo reloj vectorial de la réplica primaria.
type RespuestaGuardar struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Exito            bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	NuevoRelojVector []byte                 `protobuf:"bytes,2,opt,name=nuevoRelojVector,proto3" json:"nuevoRelojVector,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RespuestaGuardar) Reset() {
	*x = RespuestaGuardar{}
	mi := &file_proto_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaGuardar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaGuardar) ProtoMessage() {}

func (x *RespuestaGuardar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaGuardar.ProtoReflect.Descriptor instead.
func (*RespuestaGuardar) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{3}
}

func (x *RespuestaGuardar) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *RespuestaGuardar) GetNuevoRelojVector() []byte {
	if x != nil {
		return x.NuevoRelojVector
	}
	return nil
}

// Solicitud para Eliminar una clave.
type SolicitudEliminar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Clave         string                 `protobuf:"bytes,1,opt,name=clave,proto3" json:"clave,omitempty"`
	RelojVector   []byte                 `protobuf:"bytes,2,opt,name=relojVector,proto3" json:"relojVector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolicitudEliminar) Reset() {
	*x = SolicitudEliminar{}
	mi := &file_proto_kv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolicitudEliminar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolicitudEliminar) ProtoMessage() {}

func (x *SolicitudEliminar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolicitudEliminar.ProtoReflect.Descriptor instead.
func (*SolicitudEliminar) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{4}
}

func (x *SolicitudEliminar) GetClave() string {
	if x != nil {
		return x.Clave
	}
	return ""
}

func (x *SolicitudEliminar) GetRelojVector() []byte {
	if x != nil {
		return x.RelojVector
	}
	return nil
}

// Respuesta de Eliminar: éxito y nuevo reloj vectorial.
type RespuestaEliminar struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Exito            bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	NuevoRelojVector []byte                 `protobuf:"bytes,2,opt,name=nuevoRelojVector,proto3" json:"nuevoRelojVector,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RespuestaEliminar) Reset() {
	*x = RespuestaEliminar{}
	mi := &file_proto_kv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespuestaEliminar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespuestaEliminar) ProtoMessage() {}

func (x *RespuestaEliminar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespuestaEliminar.ProtoReflect.Descriptor instead.
func (*RespuestaEliminar) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{5}
}

func (x *RespuestaEliminar) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *RespuestaEliminar) GetNuevoRelojVector() []byte {
	if x != nil {
		return x.NuevoRelojVector
	}
	return nil
}

type Mutacion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tipo          Mutacion_Tipo          `protobuf:"varint,1,opt,name=tipo,proto3,enum=kv.Mutacion_Tipo" json:"tipo,omitempty"`
	Clave         string                 `protobuf:"bytes,2,opt,name=clave,proto3" json:"clave,omitempty"`
	Valor         []byte                 `protobuf:"bytes,3,opt,name=valor,proto3" json:"valor,omitempty"`             // Solo para GUARDAR
	RelojVector   []byte                 `protobuf:"bytes,4,opt,name=relojVector,proto3" json:"relojVector,omitempty"` // Reloj vectorial que asigna la réplica origen
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mutacion) Reset() {
	*x = Mutacion{}
	mi := &file_proto_kv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mutacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutacion) ProtoMessage() {}

func (x *Mutacion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutacion.ProtoReflect.Descriptor instead.
func (*Mutacion) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{6}
}

func (x *Mutacion) GetTipo() Mutacion_Tipo {
	if x != nil {
		return x.Tipo
	}
	return Mutacion_GUARDAR
}

func (x *Mutacion) GetClave() string {
	if x != nil {
		return x.Clave
	}
	return ""
}

func (x *Mutacion) GetValor() []byte {
	if x != nil {
		return x.Valor
	}
	return nil
}

func (x *Mutacion) GetRelojVector() []byte {
	if x != nil {
		return x.RelojVector
	}
	return nil
}

// Reconocimiento que envía la réplica destino
type Reconocimiento struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ok             bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	RelojVectorAck []byte                 `protobuf:"bytes,2,opt,name=relojVectorAck,proto3" json:"relojVectorAck,omitempty"` // Reloj vectorial actualizado de la réplica destino
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Reconocimiento) Reset() {
	*x = Reconocimiento{}
	mi := &file_proto_kv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reconocimiento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reconocimiento) ProtoMessage() {}

func (x *Reconocimiento) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reconocimiento.ProtoReflect.Descriptor instead.
func (*Reconocimiento) Descriptor() ([]byte, []int) {
	return file_proto_kv_proto_rawDescGZIP(), []int{7}
}

func (x *Reconocimiento) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Reconocimiento) GetRelojVectorAck() []byte {
	if x != nil {
		return x.RelojVectorAck
	}
	return nil
}

var File_proto_kv_proto protoreflect.FileDescriptor

const file_proto_kv_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/kv.proto\x12\x02kv\"(\n" +
	"\x10SolicitudObtener\x12\x14\n" +
	"\x05clave\x18\x01 \x01(\tR\x05clave\"b\n" +
	"\x10RespuestaObtener\x12\x14\n" +
	"\x05valor\x18\x01 \x01(\fR\x05valor\x12 \n" +
	"\vrelojVector\x18\x02 \x01(\fR\vrelojVector\x12\x16\n" +
	"\x06existe\x18\x03 \x01(\bR\x06existe\"`\n" +
	"\x10SolicitudGuardar\x12\x14\n" +
	"\x05clave\x18\x01 \x01(\tR\x05clave\x12\x14\n" +
	"\x05valor\x18\x02 \x01(\fR\x05valor\x12 \n" +
	"\vrelojVector\x18\x03 \x01(\fR\vrelojVector\"T\n" +
	"\x10RespuestaGuardar\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12*\n" +
	"\x10nuevoRelojVector\x18\x02 \x01(\fR\x10nuevoRelojVector\"K\n" +
	"\x11SolicitudEliminar\x12\x14\n" +
	"\x05clave\x18\x01 \x01(\tR\x05clave\x12 \n" +
	"\vrelojVector\x18\x02 \x01(\fR\vrelojVector\"U\n" +
	"\x11RespuestaEliminar\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12*\n" +
	"\x10nuevoRelojVector\x18\x02 \x01(\fR\x10nuevoRelojVector\"\xa2\x01\n" +
	"\bMutacion\x12%\n" +
	"\x04tipo\x18\x01 \x01(\x0e2\x11.kv.Mutacion.TipoR\x04tipo\x12\x14\n" +
	"\x05clave\x18\x02 \x01(\tR\x05clave\x12\x14\n" +
	"\x05valor\x18\x03 \x01(\fR\x05valor\x12 \n" +
	"\vrelojVector\x18\x04 \x01(\fR\vrelojVector\"!\n" +
	"\x04Tipo\x12\v\n" +
	"\aGUARDAR\x10\x00\x12\f\n" +
	"\bELIMINAR\x10\x01\"H\n" +
	"\x0eReconocimiento\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12&\n" +
	"\x0erelojVectorAck\x18\x02 \x01(\fR\x0erelojVectorAck2\xbb\x01\n" +
	"\vCoordinador\x127\n" +
	"\aObtener\x12\x14.kv.SolicitudObtener\x1a\x14.kv.RespuestaObtener\"\x00\x127\n" +
	"\aGuardar\x12\x14.kv.SolicitudGuardar\x1a\x14.kv.RespuestaGuardar\"\x00\x12:\n" +
	"\bEliminar\x12\x15.kv.SolicitudEliminar\x1a\x15.kv.RespuestaEliminar\"\x002\xfe\x01\n" +
	"\aReplica\x126\n" +
	"\x10ReplicarMutacion\x12\f.kv.Mutacion\x1a\x12.kv.Reconocimiento\"\x00\x12<\n" +
	"\fObtenerLocal\x12\x14.kv.SolicitudObtener\x1a\x14.kv.RespuestaObtener\"\x00\x12<\n" +
	"\fGuardarLocal\x12\x14.kv.SolicitudGuardar\x1a\x14.kv.RespuestaGuardar\"\x00\x12?\n" +
	"\rEliminarLocal\x12\x15.kv.SolicitudEliminar\x1a\x15.kv.RespuestaEliminar\"\x00B\tZ\a./protob\x06proto3"

var (
	file_proto_kv_proto_rawDescOnce sync.Once
	file_proto_kv_proto_rawDescData []byte
)

func file_proto_kv_proto_rawDescGZIP() []byte {
	file_proto_kv_proto_rawDescOnce.Do(func() {
		file_proto_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kv_proto_rawDesc), len(file_proto_kv_proto_rawDesc)))
	})
	return file_proto_kv_proto_rawDescData
}

var file_proto_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_kv_proto_goTypes = []any{
	(Mutacion_Tipo)(0),        // 0: kv.Mutacion.Tipo
	(*SolicitudObtener)(nil),  // 1: kv.SolicitudObtener
	(*RespuestaObtener)(nil),  // 2: kv.RespuestaObtener
	(*SolicitudGuardar)(nil),  // 3: kv.SolicitudGuardar
	(*RespuestaGuardar)(nil),  // 4: kv.RespuestaGuardar
	(*SolicitudEliminar)(nil), // 5: kv.SolicitudEliminar
	(*RespuestaEliminar)(nil), // 6: kv.RespuestaEliminar
	(*Mutacion)(nil),          // 7: kv.Mutacion
	(*Reconocimiento)(nil),    // 8: kv.Reconocimiento
}
var file_proto_kv_proto_depIdxs = []int32{
	0, // 0: kv.Mutacion.tipo:type_name -> kv.Mutacion.Tipo
	1, // 1: kv.Coordinador.Obtener:input_type -> kv.SolicitudObtener
	3, // 2: kv.Coordinador.Guardar:input_type -> kv.SolicitudGuardar
	5, // 3: kv.Coordinador.Eliminar:input_type -> kv.SolicitudEliminar
	7, // 4: kv.Replica.ReplicarMutacion:input_type -> kv.Mutacion
	1, // 5: kv.Replica.ObtenerLocal:input_type -> kv.SolicitudObtener
	3, // 6: kv.Replica.GuardarLocal:input_type -> kv.SolicitudGuardar
	5, // 7: kv.Replica.EliminarLocal:input_type -> kv.SolicitudEliminar
	2, // 8: kv.Coordinador.Obtener:output_type -> kv.RespuestaObtener
	4, // 9: kv.Coordinador.Guardar:output_type -> kv.RespuestaGuardar
	6, // 10: kv.Coordinador.Eliminar:output_type -> kv.RespuestaEliminar
	8, // 11: kv.Replica.ReplicarMutacion:output_type -> kv.Reconocimiento
	2, // 12: kv.Replica.ObtenerLocal:output_type -> kv.RespuestaObtener
	4, // 13: kv.Replica.GuardarLocal:output_type -> kv.RespuestaGuardar
	6, // 14: kv.Replica.EliminarLocal:output_type -> kv.RespuestaEliminar
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_kv_proto_init() }
func file_proto_kv_proto_init() {
	if File_proto_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kv_proto_rawDesc), len(file_proto_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_kv_proto_goTypes,
		DependencyIndexes: file_proto_kv_proto_depIdxs,
		EnumInfos:         file_proto_kv_proto_enumTypes,
		MessageInfos:      file_proto_kv_proto_msgTypes,
	}.Build()
	File_proto_kv_proto = out.File
	file_proto_kv_proto_goTypes = nil
	file_proto_kv_proto_depIdxs = nil
}
