// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/servicio.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Requerimiento struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Requerimiento) Reset() {
	*x = Requerimiento{}
	mi := &file_proto_servicio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Requerimiento) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Requerimiento) ProtoMessage() {}

func (x *Requerimiento) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servicio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Requerimiento.ProtoReflect.Descriptor instead.
func (*Requerimiento) Descriptor() ([]byte, []int) {
	return file_proto_servicio_proto_rawDescGZIP(), []int{0}
}

func (x *Requerimiento) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type Respuesta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	mi := &file_proto_servicio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servicio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_proto_servicio_proto_rawDescGZIP(), []int{1}
}

func (x *Respuesta) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type Vacio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vacio) Reset() {
	*x = Vacio{}
	mi := &file_proto_servicio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vacio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vacio) ProtoMessage() {}

func (x *Vacio) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servicio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vacio.ProtoReflect.Descriptor instead.
func (*Vacio) Descriptor() ([]byte, []int) {
	return file_proto_servicio_proto_rawDescGZIP(), []int{2}
}

type Lista struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Personas      []string               `protobuf:"bytes,1,rep,name=personas,proto3" json:"personas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lista) Reset() {
	*x = Lista{}
	mi := &file_proto_servicio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lista) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lista) ProtoMessage() {}

func (x *Lista) ProtoReflect() protoreflect.Message {
	mi := &file_proto_servicio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lista.ProtoReflect.Descriptor instead.
func (*Lista) Descriptor() ([]byte, []int) {
	return file_proto_servicio_proto_rawDescGZIP(), []int{3}
}

func (x *Lista) GetPersonas() []string {
	if x != nil {
		return x.Personas
	}
	return nil
}

var File_proto_servicio_proto protoreflect.FileDescriptor

const file_proto_servicio_proto_rawDesc = "" +
	"\n" +
	"\x14proto/servicio.proto\x12\bservicio\"'\n" +
	"\rRequerimiento\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\"%\n" +
	"\tRespuesta\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje\"\a\n" +
	"\x05Vacio\"#\n" +
	"\x05Lista\x12\x1a\n" +
	"\bpersonas\x18\x01 \x03(\tR\bpersonas2u\n" +
	"\bServicio\x124\n" +
	"\x04Hola\x12\x17.servicio.Requerimiento\x1a\x13.servicio.Respuesta\x123\n" +
	"\x0fListadoPersonas\x12\x0f.servicio.Vacio\x1a\x0f.servicio.ListaB\tZ\a./protob\x06proto3"

var (
	file_proto_servicio_proto_rawDescOnce sync.Once
	file_proto_servicio_proto_rawDescData []byte
)

func file_proto_servicio_proto_rawDescGZIP() []byte {
	file_proto_servicio_proto_rawDescOnce.Do(func() {
		file_proto_servicio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_servicio_proto_rawDesc), len(file_proto_servicio_proto_rawDesc)))
	})
	return file_proto_servicio_proto_rawDescData
}

var file_proto_servicio_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_servicio_proto_goTypes = []any{
	(*Requerimiento)(nil), // 0: servicio.Requerimiento
	(*Respuesta)(nil),     // 1: servicio.Respuesta
	(*Vacio)(nil),         // 2: servicio.Vacio
	(*Lista)(nil),         // 3: servicio.Lista
}
var file_proto_servicio_proto_depIdxs = []int32{
	0, // 0: servicio.Servicio.Hola:input_type -> servicio.Requerimiento
	2, // 1: servicio.Servicio.ListadoPersonas:input_type -> servicio.Vacio
	1, // 2: servicio.Servicio.Hola:output_type -> servicio.Respuesta
	3, // 3: servicio.Servicio.ListadoPersonas:output_type -> servicio.Lista
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_servicio_proto_init() }
func file_proto_servicio_proto_init() {
	if File_proto_servicio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_servicio_proto_rawDesc), len(file_proto_servicio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_servicio_proto_goTypes,
		DependencyIndexes: file_proto_servicio_proto_depIdxs,
		MessageInfos:      file_proto_servicio_proto_msgTypes,
	}.Build()
	File_proto_servicio_proto = out.File
	file_proto_servicio_proto_goTypes = nil
	file_proto_servicio_proto_depIdxs = nil
}
